name = "gament" # 确保这个名称与你在 Cloudflare 界面设置的一致
main = "_worker.js" # 或者你重命名后的文件路径，例如 "index.js"
compatibility_date = "2025-04-02" # 设置一个近期的日期，例如 "2023-10-30"
#account_id = "de9630c3e0e6f9e697d83df3497720d7" # 你需要填入你的 Account ID

# 推荐方式：在环境块中配置
[env.production]
# --- 指定域名所在的 Zone ID ---
zone_id = "4d7a662ed9d3a97a90e5a2f13fdd5d2e" # <--- 将这里替换为你复制的 Zone ID
# --- 定义路由规则 ---
routes = [
  # 示例 1: 将子域名 worker.mydomain.com 下的所有请求路由到此 Worker
  { pattern = "kun.anglosaxo.dpdns.org/*", script = "gament" },

  # 示例 2: 将主域名下 /api/ 路径的所有请求路由到此 Worker
  { pattern = "anglosaxo.dpdns.org/api/*", script = "gament" },

  # 示例 3: 将另一个子域名 app.mydomain.com 的特定路径路由到此 Worker
  # { pattern = "app.mydomain.com/worker-stuff/*", script = "epeius" }
]
